project_id = "gffwlerzqpydiewtyytv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.cerebras-chat]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15